/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package skip.reality.project.sw;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.*;

/**
 *
 * @author DesTrUcTioN
 */
public class Login extends javax.swing.JFrame {

    Connection connect=null;
    ResultSet rs=null;
    PreparedStatement st=null;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        usernamefield = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        passwordfield = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        loginbutton = new javax.swing.JToggleButton();
        registerfield = new javax.swing.JToggleButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Login Page");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(250, 10, 130, 30);

        usernamefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernamefieldActionPerformed(evt);
            }
        });
        getContentPane().add(usernamefield);
        usernamefield.setBounds(190, 80, 170, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Enter User Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 80, 130, 17);
        getContentPane().add(passwordfield);
        passwordfield.setBounds(190, 140, 170, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Enter Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 150, 120, 17);

        loginbutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        loginbutton.setText("Login");
        loginbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(loginbutton);
        loginbutton.setBounds(210, 220, 150, 30);

        registerfield.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        registerfield.setText("Register");
        registerfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerfieldActionPerformed(evt);
            }
        });
        getContentPane().add(registerfield);
        registerfield.setBounds(60, 220, 114, 30);

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox1.setText("Remember Password");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1);
        jCheckBox1.setBounds(210, 280, 200, 23);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/skip/reality/project/sw/Logo.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 620, 350);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernamefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernamefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernamefieldActionPerformed

    private void loginbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbuttonActionPerformed
        // TODO add your handling code here:
        connect = MysqlConnect.ConnectDB();
        String Sql = "SELECT * FROM user_account WHERE User_Name=? and Password=? ";
                
        try{
            
            st= connect.prepareStatement(Sql);
            
            st.setString(1,usernamefield.getText());
            st.setString(2,passwordfield.getText());
            
            rs=st.executeQuery();
            
            if(rs.next()){
                
                if(jCheckBox1.isSelected()){
                    
                JOptionPane.showMessageDialog(null,"Welcome In Our System");
                UserProfile user_info =new UserProfile();
                user_info.setVisible(true);
                
                }else{

                passwordfield.setText("");
                usernamefield.setText("");    
                JOptionPane.showMessageDialog(null,"Welcome");
                UserProfile user_info =new UserProfile();
                user_info.setVisible(true); 
                close();
  
                }
                
                
                
                
            }
            else{
                
                JOptionPane.showMessageDialog(null,"Wrong Data!\nClick OK and try again","Wrong Pass",JOptionPane.ERROR_MESSAGE);
                //passwordfield.setText("");
                //usernamefield.setText("");
            }
            
        }catch(Exception e) {
            
            JOptionPane.showMessageDialog(null,"Error");
        }
        
        
        
    }//GEN-LAST:event_loginbuttonActionPerformed

    private void registerfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerfieldActionPerformed
        // TODO add your handling code here:
            JOptionPane.showMessageDialog(null,"Press OK To Go..");
            Registration user_register =new Registration();
            user_register.setVisible(true);
        
    }//GEN-LAST:event_registerfieldActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton loginbutton;
    private javax.swing.JPasswordField passwordfield;
    private javax.swing.JToggleButton registerfield;
    private javax.swing.JTextField usernamefield;
    // End of variables declaration//GEN-END:variables

private void close(){
    
    WindowEvent Closing = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
    Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(Closing);
}

}



